import type { Schema } from "../schema";

import type {
  ItemSchema,
  ControlSchema,
  ListSchema,
  ConditionSchema,
  LoopSchema,
  SwitchSchema,
  FormSchema,
  YieldSchema,
  ReturnSchema,
  VariablesSchema,
  JumpSchema,
} from "../schema";

import type { OnNext, OnBack, GetState, SetState } from "../render";

/**
 * Defines the structure and behavior of a multi-step form.
 *
 * @template T The type of the rendered output for each form step. This can vary depending on
 * the framework; for example, in React, it would typically be `ReactNode`.
 *
 * @template U A type extending `Schema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template V An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template W An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type Flow<
  T,
  U extends Schema,
  V extends Record<string, unknown> = Record<never, never>,
  W extends Record<string, unknown> = Record<never, never>,
> = ListFlow<T, U, V, V, W>;

export type ItemFlow<
  Render,
  Schema extends ItemSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = Schema extends ControlSchema
  ? ControlFlow<Render, Schema, Inputs, Memory, Params>
  : Schema extends FormSchema
  ? FormFlow<Render, Schema, Memory, Params>
  : Schema extends YieldSchema
  ? YieldFlow<Schema, Memory>
  : Schema extends ReturnSchema
  ? ReturnFlow<Schema, Memory>
  : Schema extends VariablesSchema
  ? VariablesFlow<Schema, Memory>
  : Schema extends JumpSchema
  ? JumpFlow<Render, Schema, Inputs, Params>
  : never;

export type ControlFlow<
  Render,
  Schema extends ItemSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = Schema extends ListSchema
  ? ListFlow<Render, Schema, Inputs, Memory, Params>
  : Schema extends ConditionSchema
  ? ConditionFlow<Render, Schema, Inputs, Memory, Params>
  : Schema extends LoopSchema
  ? LoopFlow<Render, Schema, Inputs, Memory, Params>
  : Schema extends SwitchSchema
  ? SwitchFlow<Render, Schema, Inputs, Memory, Params>
  : never;

export type ListFlow<
  Render,
  Schema extends ListSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = Schema extends [infer Head, ...infer Others]
  ? Head extends ItemSchema
    ? Others extends ListSchema
      ? [
          ItemFlow<Render, Head, Inputs, Memory, Params>,
          ...ListFlow<
            Render,
            Others,
            Inputs,
            Output<Head, Inputs, Memory>,
            Params
          >,
        ]
      : never
    : never
  : [];

export type ConditionFlow<
  Render,
  Schema extends ConditionSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = {
  condition: {
    if: (inputs: Inputs) => boolean;
    then: ListFlow<Render, Schema["condition"]["then"], Inputs, Memory, Params>;
    else: ListFlow<Render, Schema["condition"]["else"], Inputs, Memory, Params>;
  };
};

export type LoopFlow<
  Render,
  Schema extends LoopSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = {
  loop: {
    while: (inputs: Inputs) => boolean;
    do: ListFlow<Render, Schema["loop"]["do"], Inputs, Memory, Params>;
  };
};

export type SwitchFlow<
  Render,
  Schema extends SwitchSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = {
  switch: {
    branches: SwitchBranchesFlow<
      Render,
      Schema["switch"]["branches"],
      Inputs,
      Memory,
      Params
    >;
    default: ListFlow<
      Render,
      Schema["switch"]["default"],
      Inputs,
      Memory,
      Params
    >;
  };
};

type SwitchBranchesFlow<
  Render,
  Schema extends ListSchema[],
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = Schema extends [infer Head, ...infer Others]
  ? Head extends ListSchema
    ? Others extends ListSchema[]
      ? [
          {
            case: (inputs: Inputs) => boolean;
            then: ListFlow<Render, Head, Inputs, Memory, Params>;
          },
          ...SwitchBranchesFlow<Render, Others, Inputs, Memory, Params>,
        ]
      : never
    : never
  : [];

export type FormFlow<
  Render,
  Schema extends FormSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = {
  form: {
    values: (inputs: Inputs) => {
      [K in keyof Schema["form"]]: [Schema["form"][K], PropertyKey[]];
    };
    render: (args: {
      inputs: Inputs;
      values: Schema["form"];
      params: Params;
      onNext: OnNext<Schema["form"]>;
      onBack: OnBack<Schema["form"]>;
      getState: GetState<Schema["form"]>;
      setState: SetState;
    }) => Render;
  };
};

export type YieldFlow<
  Schema extends YieldSchema,
  Inputs extends Record<string, unknown>,
> = {
  yield: {
    next: (inputs: Inputs) => Schema["yield"]["next"];
    back: (inputs: Inputs) => Schema["yield"]["back"];
  };
};

export type ReturnFlow<
  Schema extends ReturnSchema,
  Inputs extends Record<string, unknown>,
> = {
  return: (inputs: Inputs) => Schema["return"];
};

export type VariablesFlow<
  Schema extends VariablesSchema,
  Inputs extends Record<string, unknown>,
> = {
  variables: (inputs: Inputs) => Schema["variables"];
};

export type JumpFlow<
  Render,
  Schema extends JumpSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = {
  jump: {
    id: string;
    item: ItemFlow<Render, Schema["item"], Inputs, Inputs, Params>;
  };
};

type Output<
  Schema extends ItemSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
> = Schema extends FormSchema
  ? FormOutput<Schema, Memory>
  : Schema extends VariablesSchema
  ? VariablesOutput<Schema, Memory>
  : Schema extends ConditionSchema
  ? ConditionOutput<Schema, Inputs, Memory>
  : Schema extends LoopSchema
  ? LoopOutput<Schema, Inputs, Memory>
  : Schema extends SwitchSchema
  ? SwitchOutput<Schema, Inputs, Memory>
  : Schema extends JumpSchema
  ? Inputs
  : Memory;

type FormOutput<
  Schema extends FormSchema,
  Memory extends Record<string, unknown>,
> = Join<Schema["form"], Memory>;

type VariablesOutput<
  Schema extends VariablesSchema,
  Memory extends Record<string, unknown>,
> = Join<Schema["variables"], Memory>;

type ConditionOutput<
  Schema extends ConditionSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
> = BranchesContainsJump<
  [Schema["condition"]["then"], Schema["condition"]["else"]]
> extends true
  ? Inputs
  : Memory;

type LoopOutput<
  Schema extends LoopSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
> = ListContainsJump<Schema["loop"]["do"]> extends true ? Inputs : Memory;

type SwitchOutput<
  Schema extends SwitchSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
> = BranchesContainsJump<
  [...Schema["switch"]["branches"], Schema["switch"]["default"]]
> extends true
  ? Inputs
  : Memory;

type BranchesContainsJump<Series extends ListSchema[]> = Series extends [
  infer Head,
  ...infer Others,
]
  ? Head extends ListSchema
    ? Others extends ListSchema[]
      ? ListContainsJump<Head> extends true
        ? true
        : BranchesContainsJump<Others>
      : never
    : never
  : false;

type ListContainsJump<Schema extends ListSchema> = Schema extends [
  infer Head,
  ...infer Others,
]
  ? Head extends ItemSchema
    ? Others extends ListSchema
      ? Head extends JumpSchema
        ? true
        : ListContainsJump<Others>
      : never
    : never
  : false;

type Join<
  T extends Record<string, unknown>,
  U extends Record<string, unknown>,
> = Omit<T, keyof U> & U;
