import type { Schema } from "../schema";

import type {
  ItemSchema,
  ControlSchema,
  ListSchema,
  ConditionSchema,
  LoopSchema,
  SwitchSchema,
  FormSchema,
  YieldSchema,
  ReturnSchema,
  VariablesSchema,
} from "../schema";

import type { OnNext, OnBack, GetState, SetState } from "../render";

/**
 * Defines the structure and behavior of a multi-step form.
 *
 * @template T The type of the rendered output for each form step. This can vary depending on
 * the framework; for example, in React, it would typically be `ReactNode`.
 *
 * @template U A type extending `Schema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template V An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template W An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type Flow<
  T,
  U extends Schema,
  V extends Record<string, unknown> = Record<never, never>,
  W extends Record<string, unknown> = Record<never, never>,
> = ListFlow<T, U, V, W>;

/**
 * Defines the structure and behavior of any element in a multi-step form.
 *
 * @template Render The type of the rendered output for each form step. This can vary depending on
 * the framework; for example, in React, it would typically be `ReactNode`.
 *
 * @template Schema A type extending `ItemSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type ItemFlow<
  Render,
  Schema extends ItemSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = Schema extends ControlSchema
  ? ControlFlow<Render, Schema, Inputs, Params>
  : Schema extends FormSchema
  ? FormFlow<Render, Schema, Inputs, Params>
  : Schema extends YieldSchema
  ? YieldFlow<Schema, Inputs>
  : Schema extends ReturnSchema
  ? ReturnFlow<Schema, Inputs>
  : Schema extends VariablesSchema
  ? VariablesFlow<Schema, Inputs>
  : never;

/**
 * Defines the structure and behavior of any control element in a multi-step form.
 *
 * @template Render The type of the rendered output for each form step. This can vary depending on
 * the framework; for example, in React, it would typically be `ReactNode`.
 *
 * @template Schema A type extending `ItemSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type ControlFlow<
  Render,
  Schema extends ItemSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = Schema extends ListSchema
  ? ListFlow<Render, Schema, Inputs, Params>
  : Schema extends ConditionSchema
  ? ConditionFlow<Render, Schema, Inputs, Params>
  : Schema extends LoopSchema
  ? LoopFlow<Render, Schema, Inputs, Params>
  : Schema extends SwitchSchema
  ? SwitchFlow<Render, Schema, Inputs, Params>
  : never;

/**
 * Defines the structure and behavior of a list element in a multi-step form.
 *
 * @template Render The type of the rendered output for each form step. This can vary depending on
 * the framework; for example, in React, it would typically be `ReactNode`.
 *
 * @template Schema A type extending `ListSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type ListFlow<
  Render,
  Schema extends ListSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = Schema extends [infer Head, ...infer Others]
  ? Head extends ItemSchema
    ? Others extends ListSchema
      ? [
          ItemFlow<Render, Head, Inputs, Params>,
          ...ListFlow<Render, Others, Joined<Inputs, ItemOutput<Head>>, Params>,
        ]
      : never
    : never
  : [];

/**
 * Defines the structure and behavior of a condition element in a multi-step form.
 *
 * @template Render The type of the rendered output for each form step. This can vary depending on
 * the framework; for example, in React, it would typically be `ReactNode`.
 *
 * @template Schema A type extending `CondSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type ConditionFlow<
  Render,
  Schema extends ConditionSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = {
  condition: {
    if: (inputs: Inputs) => boolean;
    then: ListFlow<Render, Schema["cond"]["then"], Inputs, Params>;
    else: ListFlow<Render, Schema["cond"]["else"], Inputs, Params>;
  };
};

/**
 * Defines the structure and behavior of a loop element in a multi-step form.
 *
 * @template Render The type of the rendered output for each form step. This can vary depending on
 * the framework; for example, in React, it would typically be `ReactNode`.
 *
 * @template Schema A type extending `LoopSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type LoopFlow<
  Render,
  Schema extends LoopSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = {
  loop: {
    while: (inputs: Inputs) => boolean;
    do: ListFlow<Render, Schema["loop"]["do"], Inputs, Params>;
  };
};

/**
 * Defines the structure and behavior of a switch element in a multi-step form.
 *
 * @template Render The type of the rendered output for each form step. This can vary depending on
 * the framework; for example, in React, it would typically be `ReactNode`.
 *
 * @template Schema A type extending `SwitchSchema` that defines the structure of the multi-step
 * form, including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type SwitchFlow<
  Render,
  Schema extends SwitchSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = {
  switch: {
    branches: SwitchBranchesFlow<
      Render,
      Schema["switch"]["branches"],
      Inputs,
      Params
    >;
    default: ListFlow<Render, Schema["switch"]["default"], Inputs, Params>;
  };
};

type SwitchBranchesFlow<
  Render,
  Schema extends ListSchema[],
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = Schema extends [infer Head, ...infer Others]
  ? Head extends ListSchema
    ? Others extends ListSchema[]
      ? [
          {
            case: (inputs: Inputs) => boolean;
            then: ListFlow<Render, Head, Inputs, Params>;
          },
          ...SwitchBranchesFlow<Render, Others, Inputs, Params>,
        ]
      : never
    : never
  : [];

/**
 * Defines the structure and behavior of a form element in a multi-step form.
 *
 * @template Render The type of the rendered output for each form step. This can vary depending on
 * the framework; for example, in React, it would typically be `ReactNode`.
 *
 * @template Schema A type extending `FormSchema` that defines the values of the form element.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type FormFlow<
  Render,
  Schema extends FormSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = {
  form: {
    values: (inputs: Inputs) => {
      [K in keyof Schema["form"]]: [Schema["form"][K], PropertyKey[]];
    };
    render: (args: {
      inputs: Inputs;
      values: Schema["form"];
      params: Params;
      onNext: OnNext<Schema["form"]>;
      onBack: OnBack<Schema["form"]>;
      getState: GetState<Schema["form"]>;
      setState: SetState;
    }) => Render;
  };
};

/**
 * Defines the structure and behavior of a yield element in a multi-step form.
 *
 * @template Schema A type extending `YieldSchema` that defines the values of the yield element.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 */
export type YieldFlow<
  Schema extends YieldSchema,
  Inputs extends Record<string, unknown>,
> = {
  yield: {
    next: (inputs: Inputs) => Schema["yield"]["next"];
    back: (inputs: Inputs) => Schema["yield"]["back"];
  };
};

/**
 * Defines the structure and behavior of a return element in a multi-step form.
 *
 * @template Schema A type extending `ReturnSchema` that defines the values of the return element.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 */
export type ReturnFlow<
  Schema extends ReturnSchema,
  Inputs extends Record<string, unknown>,
> = {
  return: (inputs: Inputs) => Schema["return"];
};

/**
 * Defines the structure and behavior of a variables element in a multi-step form.
 *
 * @template Schema A type extending `VariablesSchema` that defines the values of the variables element.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 */
export type VariablesFlow<
  Schema extends VariablesSchema,
  Inputs extends Record<string, unknown>,
> = {
  variables: (inputs: Inputs) => Schema["variables"];
};

type Joined<
  T extends Record<string, unknown>,
  U extends Record<string, unknown>,
> = Omit<T, keyof U> & U;

type ItemOutput<Schema extends ItemSchema> = Schema extends FormSchema
  ? FormOutput<Schema>
  : Schema extends VariablesSchema
  ? VariablesOutput<Schema>
  : Record<never, never>;

type FormOutput<Schema extends FormSchema> = Schema["form"];
type VariablesOutput<Schema extends VariablesSchema> = Schema["variables"];
