import type { ReactNode } from "react";

import type { Schema } from "@formity/system";

import type { Flow as SystemFlow } from "@formity/system";

/**
 * Defines the structure and behavior of a multi-step form.
 *
 * @template Struct A type extending `Schema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type Flow<
  Struct extends Schema,
  Inputs extends Record<string, unknown> = Record<never, never>,
  Params extends Record<string, unknown> = Record<never, never>,
> = SystemFlow<ReactNode, Struct, Inputs, Params>;
