import type { ReactNode } from "react";

import type { Schema } from "@formity/system";

import type {
  ItemSchema,
  ControlSchema,
  ListSchema,
  ConditionSchema,
  LoopSchema,
  SwitchSchema,
  FormSchema,
  YieldSchema,
  ReturnSchema,
  VariablesSchema,
} from "@formity/system";

import type { Flow as SystemFlow } from "@formity/system";

import type {
  ItemFlow as SystemItemFlow,
  ControlFlow as SystemControlFlow,
  ListFlow as SystemListFlow,
  ConditionFlow as SystemConditionFlow,
  LoopFlow as SystemLoopFlow,
  SwitchFlow as SystemSwitchFlow,
  FormFlow as SystemFormFlow,
  YieldFlow as SystemYieldFlow,
  ReturnFlow as SystemReturnFlow,
  VariablesFlow as SystemVariablesFlow,
} from "@formity/system";

import type { ModelFlow as SystemModelFlow } from "@formity/system";

import type {
  ModelItemFlow as SystemModelItemFlow,
  ModelControlFlow as SystemModelControlFlow,
  ModelListFlow as SystemModelListFlow,
  ModelConditionFlow as SystemModelConditionFlow,
  ModelLoopFlow as SystemModelLoopFlow,
  ModelSwitchFlow as SystemModelSwitchFlow,
  ModelFormFlow as SystemModelFormFlow,
  ModelYieldFlow as SystemModelYieldFlow,
  ModelReturnFlow as SystemModelReturnFlow,
  ModelVariablesFlow as SystemModelVariablesFlow,
} from "@formity/system";

/**
 * Defines the structure and behavior of a multi-step form.
 *
 * @template T A type extending `Schema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template U An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template V An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type Flow<
  T extends Schema,
  U extends Record<string, unknown> = Record<never, never>,
  V extends Record<string, unknown> = Record<never, never>,
> = SystemFlow<ReactNode, T, U, V>;

/**
 * Defines the structure and behavior of any element in a multi-step form.
 *
 * @template Schema A type extending `ItemSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type ItemFlow<
  Schema extends ItemSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemItemFlow<ReactNode, Schema, Inputs, Params>;

/**
 * Defines the structure and behavior of any control element in a multi-step form.
 *
 * @template Schema A type extending `ControlSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type ControlFlow<
  Schema extends ControlSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemControlFlow<ReactNode, Schema, Inputs, Params>;

/**
 * Defines the structure and behavior of a list element in a multi-step form.
 *
 * @template Schema A type extending `ListSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type ListFlow<
  Schema extends ListSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemListFlow<ReactNode, Schema, Inputs, Params>;

/**
 * Defines the structure and behavior of a condition element in a multi-step form.
 *
 * @template Schema A type extending `ConditionSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type ConditionFlow<
  Schema extends ConditionSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemConditionFlow<ReactNode, Schema, Inputs, Params>;

/**
 * Defines the structure and behavior of a loop element in a multi-step form.
 *
 * @template Schema A type extending `LoopSchema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type LoopFlow<
  Schema extends LoopSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemLoopFlow<ReactNode, Schema, Inputs, Params>;

/**
 * Defines the structure and behavior of a switch element in a multi-step form.
 *
 * @template Schema A type extending `SwitchSchema` that defines the structure of the multi-step
 * form, including the values handled in each phase.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type SwitchFlow<
  Schema extends SwitchSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemSwitchFlow<ReactNode, Schema, Inputs, Params>;

/**
 * Defines the structure and behavior of a form element in a multi-step form.
 *
 * @template Schema A type extending `FormSchema` that defines the values of the form element.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template Params An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type FormFlow<
  Schema extends FormSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemFormFlow<ReactNode, Schema, Inputs, Params>;

/**
 * Defines the structure and behavior of a yield element in a multi-step form.
 *
 * @template Schema A type extending `YieldSchema` that defines the values of the yield element.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 */
export type YieldFlow<
  Schema extends YieldSchema,
  Inputs extends Record<string, unknown>,
> = SystemYieldFlow<Schema, Inputs>;

/**
 * Defines the structure and behavior of a return element in a multi-step form.
 *
 * @template Schema A type extending `ReturnSchema` that defines the values of the return element.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 */
export type ReturnFlow<
  Schema extends ReturnSchema,
  Inputs extends Record<string, unknown>,
> = SystemReturnFlow<Schema, Inputs>;

/**
 * Defines the structure and behavior of a variables element in a multi-step form.
 *
 * @template Schema A type extending `VariablesSchema` that defines the values of the variables element.
 *
 * @template Inputs An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 */
export type VariablesFlow<
  Schema extends VariablesSchema,
  Inputs extends Record<string, unknown>,
> = SystemVariablesFlow<Schema, Inputs>;

/**
 * Defines the structure and behavior of a multi-step form.
 */
export type ModelFlow = SystemModelFlow<ReactNode>;

/**
 * Defines the structure and behavior of any element in a multi-step form.
 */
export type ModelItemFlow = SystemModelItemFlow<ReactNode>;

/**
 * Defines the structure and behavior of any control element in a multi-step form.
 */
export type ModelControlFlow = SystemModelControlFlow<ReactNode>;

/**
 * Defines the structure and behavior of a list element in a multi-step form.
 */
export type ModelListFlow = SystemModelListFlow<ReactNode>;

/**
 * Defines the structure and behavior of a condition element in a multi-step form.
 */
export type ModelConditionFlow = SystemModelConditionFlow<ReactNode>;

/**
 * Defines the structure and behavior of a loop element in a multi-step form.
 */
export type ModelLoopFlow = SystemModelLoopFlow<ReactNode>;

/**
 * Defines the structure and behavior of a switch element in a multi-step form.
 */
export type ModelSwitchFlow = SystemModelSwitchFlow<ReactNode>;

/**
 * Defines the structure and behavior of a form element in a multi-step form.
 */
export type ModelFormFlow = SystemModelFormFlow<ReactNode>;

/**
 * Defines the structure and behavior of a yield element in a multi-step form.
 */
export type ModelYieldFlow = SystemModelYieldFlow;

/**
 * Defines the structure and behavior of a return element in a multi-step form.
 */
export type ModelReturnFlow = SystemModelReturnFlow;

/**
 * Defines the structure and behavior of a variables element in a multi-step form.
 */
export type ModelVariablesFlow = SystemModelVariablesFlow;
