import type { ReactNode } from "react";

import type { Schema } from "@formity/system";

import type {
  ItemSchema,
  ControlSchema,
  ListSchema,
  ConditionSchema,
  LoopSchema,
  SwitchSchema,
  FormSchema,
  YieldSchema,
  ReturnSchema,
  VariablesSchema,
  JumpSchema,
} from "@formity/system";

import type { Flow as SystemFlow } from "@formity/system";

import type {
  ItemFlow as SystemItemFlow,
  ControlFlow as SystemControlFlow,
  ListFlow as SystemListFlow,
  ConditionFlow as SystemConditionFlow,
  LoopFlow as SystemLoopFlow,
  SwitchFlow as SystemSwitchFlow,
  FormFlow as SystemFormFlow,
  YieldFlow as SystemYieldFlow,
  ReturnFlow as SystemReturnFlow,
  VariablesFlow as SystemVariablesFlow,
  JumpFlow as SystemJumpFlow,
} from "@formity/system";

import type { ModelFlow as SystemModelFlow } from "@formity/system";

import type {
  ModelItemFlow as SystemModelItemFlow,
  ModelControlFlow as SystemModelControlFlow,
  ModelListFlow as SystemModelListFlow,
  ModelConditionFlow as SystemModelConditionFlow,
  ModelLoopFlow as SystemModelLoopFlow,
  ModelSwitchFlow as SystemModelSwitchFlow,
  ModelFormFlow as SystemModelFormFlow,
  ModelYieldFlow as SystemModelYieldFlow,
  ModelReturnFlow as SystemModelReturnFlow,
  ModelVariablesFlow as SystemModelVariablesFlow,
  ModelJumpFlow as SystemModelJumpFlow,
} from "@formity/system";

/**
 * Defines the structure and behavior of a multi-step form.
 *
 * @template T A type extending `Schema` that defines the structure of the multi-step form,
 * including the values handled in each phase.
 *
 * @template U An object type representing additional values available during form execution,
 * beyond those generated by the multi-step form itself.
 *
 * @template V An object type defining the values accessible when rendering each form step in
 * the multi-step process.
 */
export type Flow<
  T extends Schema,
  U extends Record<string, unknown> = Record<never, never>,
  V extends Record<string, unknown> = Record<never, never>,
> = SystemFlow<ReactNode, T, U, V>;

export type ItemFlow<
  Schema extends ItemSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemItemFlow<ReactNode, Schema, Inputs, Memory, Params>;

export type ControlFlow<
  Schema extends ControlSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemControlFlow<ReactNode, Schema, Inputs, Memory, Params>;

export type ListFlow<
  Schema extends ListSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemListFlow<ReactNode, Schema, Inputs, Memory, Params>;

export type ConditionFlow<
  Schema extends ConditionSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemConditionFlow<ReactNode, Schema, Inputs, Memory, Params>;

export type LoopFlow<
  Schema extends LoopSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemLoopFlow<ReactNode, Schema, Inputs, Memory, Params>;

export type SwitchFlow<
  Schema extends SwitchSchema,
  Inputs extends Record<string, unknown>,
  Memory extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemSwitchFlow<ReactNode, Schema, Inputs, Memory, Params>;

export type FormFlow<
  Schema extends FormSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemFormFlow<ReactNode, Schema, Inputs, Params>;

export type YieldFlow<
  Schema extends YieldSchema,
  Inputs extends Record<string, unknown>,
> = SystemYieldFlow<Schema, Inputs>;

export type ReturnFlow<
  Schema extends ReturnSchema,
  Inputs extends Record<string, unknown>,
> = SystemReturnFlow<Schema, Inputs>;

export type VariablesFlow<
  Schema extends VariablesSchema,
  Inputs extends Record<string, unknown>,
> = SystemVariablesFlow<Schema, Inputs>;

export type JumpFlow<
  Schema extends JumpSchema,
  Inputs extends Record<string, unknown>,
  Params extends Record<string, unknown>,
> = SystemJumpFlow<ReactNode, Schema, Inputs, Params>;

export type ModelFlow = SystemModelFlow<ReactNode>;

export type ModelItemFlow = SystemModelItemFlow<ReactNode>;

export type ModelControlFlow = SystemModelControlFlow<ReactNode>;

export type ModelListFlow = SystemModelListFlow<ReactNode>;

export type ModelConditionFlow = SystemModelConditionFlow<ReactNode>;

export type ModelLoopFlow = SystemModelLoopFlow<ReactNode>;

export type ModelSwitchFlow = SystemModelSwitchFlow<ReactNode>;

export type ModelFormFlow = SystemModelFormFlow<ReactNode>;

export type ModelYieldFlow = SystemModelYieldFlow;

export type ModelReturnFlow = SystemModelReturnFlow;

export type ModelVariablesFlow = SystemModelVariablesFlow;

export type ModelJumpFlow = SystemModelJumpFlow;
